### ISSUE TITLE
Got error when having tilde (~) in YAML file.

### ISSUE THREAD

**Issue by renard** [mabragor/cl-yaclyaml#2]
I follow the quickdocs (http://quickdocs.org/cl-yaclyaml/) and I got an error if I am trying to load  a YAML file with a `~` in it:

`~/.ssh/test.yml` is:
```yaml
- host: foo
  ssh-key: '~/.ssh/id_rsa'
```
Error:
```common-lisp
CL-USER> (cl-yy::yaml-load-file "~/.ssh/test.yml" :size-limit 100 :on-size-exceed :warn)
error in FORMAT: unknown format directive (character: Space)
  Char ~ is not equal to desired char 

Char ~ is not equal to desired char 
        ^
   [Condition of type SB-FORMAT:FORMAT-ERROR]
```

Thanks in advance for your support to `cl-yaclyaml`.

Cheers

**Comment by mabragor** [comment]
Ok, this was a complex problem in esrap-liquid, actually. Please, update it and cl-yaclyaml from master branches and let me know, if something is still not working.

Best,
Alex

**Comment by renard** [comment]
After update to last git version of both `cl-yaclyaml` and `esrap-liquid` this works perfectly.

Thanks for the quick fix.
